defaults: &defaults
  working_directory: ~/openfisca-brestmetropole
  docker:
    - image: python:2.7.12

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip wheel
      - run:
          name: Install dependencies
          command: pip install . --upgrade && pip install ".[test]"
      - run:
          name: Run unit tests
          command: make test

workflows:
  version: 2
  test:
    jobs:
      - test
